
development:
  adapter: postgresql
  database: mgmschooldb
  pool: 5
  timeout: 5000
  username: mgmschooldb
  password: 


test:
  adapter: postgresql

  database: mgmschooldb

  pool: 5
  timeout: 5000
  username: mgmschooldb
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: mgmschooldb

  pool: 5
  timeout: 5000
  username: mgmschooldb
  password: 

